### ISSUE TITLE
Use the Exchange Management Shell to create a shared mailbox <- Steps Don't Appear to Work

### ISSUE THREAD

**Issue by securityvoid** [MicrosoftDocs/OfficeDocs-O365ITPro#100]
The above steps don't appear to work in Office 365 when adding a group to a shared mailbox. The PowerShell command runs successfully, but its not possible to expand the mailbox in Outlook even if you manually add the Shared Mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a258b08-9f84-d11d-a5c5-8c758dfd5d18
* Version Independent ID: 1b9620e1-c056-cb1d-72cd-623703365e79
* Content: [Create a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/create-a-shared-mailbox?view=o365-worldwide)
* Content Source: [Office365-Admin/email/create-a-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/create-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by securityvoid** [comment]
To add further details, the following will not have the group show up for the user when MarketingSG is a group:
`New-Mailbox -Shared -Name "Sales Department" -DisplayName "Sales Department" -Alias Sales | Add-MailboxPermission -User MarketingSG -AccessRights FullAccess -InheritanceType All`

If you instead change it to the following it will work:
`New-Mailbox -Shared -Name "Sales Department" -DisplayName "Sales Department" -Alias Sales | Add-MailboxPermission -User "user@domain.com" -AccessRights FullAccess -InheritanceType All`

I could not find any definitive source that stated groups were not supported on Office 365 Shared mailboxes, but several forums did suggest this was the case. As a result it may in fact be that this is not possible at all.

This seems weird to me since this is definitely possible with on-premise exchange. I'm hoping to have the same streamlined onboading procedure where I just add users to a few groups, rather than having to manually add them to a bunch of stuff. Is there a way this can be done?

**Comment by AndreaBarr** [comment]
@lindspea Could you please investigate this issue?

**Comment by lindspea** [comment]
Will do
[image: Picture]

**Comment by PsychoData** [comment]
@securityvoid  Can you confirm MarketingSG is a Mail-Enabled Security Group?  if not, what type of group is it? 

I was able to 

- add a mail-enabled security group through O365 exchange admin portal (I don't have my test tenant AAD Sync'd),
- Add that Mail-security Group as a Delegate/FullAccess to view the mailbox
- Add that mail-security group as a SendAs on Recipient Permissions for the Shared mailbox group
- Access Shared Sales@contoso.one mailbox through OWA 
- Add Sales@contoso.one as a send as in Outlook Desktop
- Add Sales Department mailbox on the side of Outlook Desktop (not through Groups, but the whole mailbox) 


![Create Shared Mailbox and add Security group to permissions](https://i.imgur.com/dqOyceC.png "Create Shared mailbox and add Security group to permissions")


![Note the timestamp](https://i.imgur.com/JX0MVFX.png "Note the timestamp")

![Add Mailbox in Outlook 1](https://i.imgur.com/1rWJhno.png "Add Mailbox in Outlook 1")
![Add Mailbox in Outlook 2](https://i.imgur.com/64PwReb.png "Add Mailbox in Outlook 2")


However, I was not able to Automap the Sales Department Mailbox based on Group Permission in my attempts. 
In Exchange on-prem environments, I think that Outlook would check the AD attributes, and expand the msexchdelegatelistlink and msExchDelegateListBL attributes, and then the Outlook client would attempt to open the additional mailboxes. 
With the O365, at least in my test setup, and possibly with an AAD Sync'd setup (because of the Group with the date that is generated), the Outlook client may not be able to enumerate the members of the sg-TestGroup and determine that he is a member to try to mount that mailbox, and manually adding it as I showed bypasses that in the meantime. 

The other possibility I see is that Exchange Online when they are "populating" the msExchDelegateLinkList for a given O365 user, they are not expanding the security group to it's members, and then adding the mailbox's delegation to it's users. And again, in this case, a workaround to bypass this if to tell your Outlook to manually open it for them, and they won't get any denied because their account HAS access, just the ExO systems didn't pass the delegation down to the group's members, and the client can't see it's in the group to check his groups members or anything like that, because it's cloud not on-prem and it's not the "real" security group, it's the date-ified version

**Comment by lindspea** [comment]
Hi @securityvoid @PsychoData Thank you for your valuable contributions in improving MS docs.  We will work together to resolve this issue.

**Comment by dariomws306** [comment]
Hi @securityvoid and @PsychoData ,

I have tried a lot different ways and the only one that doesn't work for me was using "Set-Mailbox -GrantSendOnBehalfTo MarketingSG" in the middle.

I am attaching an output file.

[out.txt](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/files/2762179/out.txt)

**Comment by dariomws306** [comment]
Ok, I found the issue. Issue here is that Set-Mailbox doesn't have output, so you cannot pipe after it Add-MailboxPermission:
https://docs.microsoft.com/en-us/exchange/client-developer/management/exchange-management-shell-cmdlet-input-and-output-types

I am proposing and update.

**Comment by dariomws306** [comment]
@PsychoData You cannot use -PassThru with Set-Mailbox. I think that the only solution is run Set-Mailbox or Add-MailboxPermission in a different line, no piping them.

**Comment by PsychoData** [comment]
Oh, I thought you meant proposing an update to the module, not to the documentation only.
