### ISSUE TITLE
Email Error 

### ISSUE THREAD

**Issue by KellyDang86** [MicrosoftDocs/OfficeDocs-O365ITPro#103]
dear Admin,
How couldnt i send the email to everybody since last weekend

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 345ba0cf-c1b8-45b2-ac51-b02dfddedf93
* Version Independent ID: 7a53dbc3-0fef-71b3-5b74-c71f0b113b70
* Content: [Support information for Vietnam](https://docs.microsoft.com/vi-vn/office365/admin/support/vietnam?view=o365-worldwide)
* Content Source: [Office365-Admin/support/vietnam.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/vietnam.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by AndreaBarr** [comment]
@KellyDang86 Thank you for this feedback

I would like to get this email issue handled for you in the best way possible. I want to get you over to Support since they have more resources than we do to dig in and find a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
