### ISSUE TITLE
Target Release for Organisation could be different to Target Release for selected Users

### ISSUE THREAD

**Issue by Benny183** [MicrosoftDocs/OfficeDocs-O365ITPro#218]
It could happen that some features are only available in Target Release for organization. There should be a noticed that this could happen and powerusers will not see all preview features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046ce912-1f0f-81b9-1126-5558e93df52a
* Version Independent ID: 755e811c-2aa0-9dc5-6846-93a6c401b01e
* Content: [Set up the Standard or Targeted release options in Office 365](https://docs.microsoft.com/en-us/office365/admin/manage/release-options-in-office-365?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/release-options-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/release-options-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by lindspea** [comment]
@Benny183 Thank you for reaching out.  I will investigate further and add the necessary information.  Thanks for your valuable contribution.

**Comment by lindspea** [comment]
@Benny183 These notes appear in the article.  Would they suffice? _[!IMPORTANT] The Office 365 updates described in this article apply to Office 365, SharePoint Online, and Exchange Online. They do not apply to Skype for Business and related services. These release options are targeted, best effort ways to release changes to Office 365 but cannot be guaranteed at all times or for all updates.
​[!IMPORTANT] Large or complex updates may take longer than others so that no users are adversely affected. There is no guarantee on the exact timeline of a release._
Please let me know if you think anything additional should be added or if you would like further assistance.

**Comment by lindspea** [comment]
@AndreaBarr @mypil this can be close thank you.
