### ISSUE TITLE
FAQ: Is it possible to enable Kaizala for a subset of users?

### ISSUE THREAD

**Issue by PiKappZ746** [MicrosoftDocs/OfficeDocs-O365ITPro#404]
I'm sure many others will ask this question, especially in large enterprises where we want to evaluate new products prior to rolling to the masses.  Is it possible to enable Kaizala for a subset of our users?  Even if it's not possible, it would be good to make that clear in the documentation as I'm sure it will be a FAQ. If it isn't currently possible, is it on the roadmap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c5fb54-20b6-527f-267e-14cfcd991e3d
* Version Independent ID: 6e7db890-accf-c27b-b84d-cf5ae4eefe84
* Content: [Enable or disable Kaizala Pro for your organization](https://docs.microsoft.com/en-us/Office365/Kaizala/enable-disable-kaizala)
* Content Source: [Office365-Kaizala/enable-disable-kaizala.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/enable-disable-kaizala.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PiKappZ746 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@chuckedmonson - Can you please share your insights on this issue? Thank you.

**Comment by chuckedmonson** [comment]
@nitinjms -- Would you please review @PiKappZ746 inquiry about a subset of users and reply as appropriate? Thank you.

**Comment by nitinjms2** [comment]
Hi Sir/Madam,

Thanks for reaching out and for the suggestion. Surely, will put it out on FAQ soon.

Kaizala, like other Office 365 products, can be enabled/disabled for the whole organization by Tenant Admin(s). However, you can control Kaizala enablement artificially by rolling it out and test your scenarios with few select users in your organisation. 

Kaizala Management Portal provides tenant admin(s) enough levers to control membership, policies to restrict your org’s group rollout to other users. However, since Kaizala mobile app can be downloaded for free on Play store/Appstore, any other users can download and start using Kaizala in personal capacity.

Hope this helps.

Thanks,
Nitin

**Comment by mypil** [comment]
@PiKappZ746 - From our understanding, the issue you raised has been nitinjms2. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
