### ISSUE TITLE
Rooms and equipment - unlicensed users

### ISSUE THREAD

**Issue by mmu69** [MicrosoftDocs/OfficeDocs-O365ITPro#474]
After creating room or equipment mailboxes they also show under: settings, users, active users 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0176b533-4c38-8f7b-f4f8-2cd62d1e698c
* Version Independent ID: b9bdbc3a-e960-4d77-e556-d5ff6dcf0e69
* Content: [Postvakken voor vergaderruimten en apparatuur](https://docs.microsoft.com/nl-nl/office365/admin/manage/room-and-equipment-mailboxes?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/room-and-equipment-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/room-and-equipment-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@mmu69 Thank you for the feedback. You are correct, The room or equipment mailbox will show up under active users (unlicensed) after they have been provisioned. The same applies to shared mailboxes as well. This is by design and a few users have requested for a design change 
  on https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/34680619-shared-mailboxes-shouldn-t-appear-in-active-users. If you also agree with this, You can upvote the uservoice and Hopefully we can have the change approved by the Product group. Hope this helps!

Regards
Sriraman MS

**Comment by mypil** [comment]
@mmu69 - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
