### ISSUE TITLE
Setting up the policy for session alive to kill upon password change.

### ISSUE THREAD

**Issue by sev7enITA** [MicrosoftDocs/OfficeDocs-O365ITPro#58]
Dear MS Team,
thanks for the usual care you have in the docs but it lacks of an important aspect: how to setup the de-sync of the active session when we have a password change.
It is very important and critical as usually left devices far from where they are and for any password change, the ones with the old credential block the account due to bad logon credentials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ae0f7d-90b6-8647-8ea5-0a3b15cd1d53
* Version Independent ID: b8c089e1-689e-96a3-f67d-c6031f0fb725
* Content: [Set the password expiration policy for your organization](https://docs.microsoft.com/en-us/office365/admin/manage/set-password-expiration-policy?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by AndreaBarr** [comment]
@sev7enITA Thank you for this feedback

I'll the get this request for more information about configuring this over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@sonika24 Could you please investigate this?

**Comment by Jcoetsee** [comment]
@kwekuako 

I'd like some insight from you regarding this please Kweku. There are plenty of methods to use in order to force all active sessions to close for a user and I wanted to see based on the question above what we can consider adding into the article. Please see the below link that shows all the examples of possible ways to disconnect sessions and let me know what your thoughts are!

This link is just for discussion, reference and example and not official:
http://www.thecloudtechnologist.com/15-things-to-do-before-and-after-a-phishing-event-in-office-365/

**Comment by mypil** [comment]
@kwekuako - can you please assist to check and share your inputs on the information provided by @Jcoetsee? Thank you.

**Comment by mypil** [comment]
@sev7enITA - From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
