### ISSUE TITLE
Show more than the default free busy

### ISSUE THREAD

**Issue by AnthonyMuscio** [MicrosoftDocs/OfficeDocs-O365ITPro#683]
We want to show more than just free busy on a resource mail box but a few of the related documentation do not address this issue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0176b533-4c38-8f7b-f4f8-2cd62d1e698c
* Version Independent ID: b9bdbc3a-e960-4d77-e556-d5ff6dcf0e69
* Content: [Room and equipment mailboxes](https://docs.microsoft.com/en-us/office365/admin/manage/room-and-equipment-mailboxes?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/room-and-equipment-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/room-and-equipment-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AnthonyMuscio - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by AnthonyMuscio** [comment]
This should be a standard practice and should be in the documentation. I will submit a ticket if I can not find out how by exploration but surely someone has a simple answer. And that should be in the documentation.

**Comment by mypil** [comment]
@AnthonyMuscio - Thank you for your response. Is there something within this article that you suggest to be added or edited? If yes, please share the appropriate text and where it should be placed, so a Pull Request can be created to get it added.

Otherwise, if your issue is more of a feature request then for user feedback on product feature requests, you can submit via **[User Voice](https://office365.uservoice.com)**.

Alternatively, if you require technical support then you can open a **[support ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)**.

Please understand that this site is a product documentation site and not a support nor a feature request site. I hope this gets you pointed in the right direction. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@officedocsbot close
