### ISSUE TITLE
λάθος χρέωση !!!

### ISSUE THREAD

**Issue by kmpaltas** [MicrosoftDocs/OfficeDocs-O365ITPro#722]
καλησπέρα μου στείλατε ένα email για αγορά microsoft office 365 με χρέωση στα 312,48  ,   εγώ όμως είχα αγοράσει ένα προϊών που είναι για 5 συσκευές με ποσό 128 ευρώ περίπου και απλά ζήτησα ανανέωση .  για πιο λόγο έχω την διπλάσια χρέωση και γιατί δεν φαίνεται στο προφίλ μου το προϊών που κοστίζει τόσο !!!!  παρακαλώ στείλτε και έναν αριθμό τηλεφώνου που μπορώ να καλώ για να λύσω τα όποια προβλήματα συναντάω γιατί ο αριθμός που αναγράφετε στην σελίδα σας δεν λειτουργεί !! ευχαριστώ πολύ 

---
#### Λεπτομέρειες εγγράφου

⚠ *Μην επεξεργαστείτε αυτή την ενότητα. Απαιτείται για σύνδεση θεμάτων docs.microsoft.com ➟ GitHub.*

* ID: 9063ef3d-c888-424f-da2f-df3bc4529192
* Version Independent ID: 5e57fadd-73ba-9152-e23e-e11554dc0596
* Content: [Support information for Greece](https://docs.microsoft.com/el-gr/office365/admin/support/greece?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/support/greece.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/greece.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@kmpaltas - Σας ευχαριστώ για την υποβολή σχολίων. [Thank you for submitting feedback.]

Θα διαβιβάσω αυτό το θέμα στην ομάδα γραφής O365 ITPro για έρευνα.
[I will forward this topic to the O365 ITPro Writing Team for research.]

Αν χρειάζεστε άμεση βοήθεια με το πρόβλημα χρέωσής σας ή εάν χρειάζεστε τεχνική υποστήριξη, μπορείτε να ανοίξετε ένα εισιτήριο υπηρεσίας στον ενοικιαστή σας, ώστε να μπορεί να επιλυθεί. Με βάση το αποτέλεσμα, επιτρέψτε μου να ξέρω αν είναι κάτι που μπορεί να κληθεί στο έγγραφο
[If you need immediate help with your billing problem or need technical support, you can open a service ticket in your tenant so that it can be resolved. Based on the result, let me know if this is something that can be called out in the document.]

Σας παρακαλούμε κάντε κλικ σε αυτόν τον [σύνδεσμο ](https://docs.microsoft.com/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online)
[Please click on this link]

**Comment by mypil** [comment]
@cmcatee-MSFT - FYI. This is a telephony issue on the Greece Support phone number.

**Comment by mypil** [comment]
@kmpaltas - Could you please let us know if this issue is still happening? and if so could you please provide us the below needed information in order to open a trouble ticket with the carrier?

1. Country and Number being called:
2. Country and City of person calling to test:
3. Number tester is calling from:
4. Landline or Mobile Phone?
5. What Carrier does this number belong to?
6. Date and time of test call:
7. Exact details of errors or experience when calling:

Greek Translation: [Ελληνική Μετάφραση:]
Θα μπορούσατε να μας ενημερώσετε εάν αυτό το ζήτημα εξακολουθεί να συμβαίνει; και αν ναι, θα μπορούσατε να μας παράσχετε τις πληροφορίες που απαιτούνται παρακάτω για να ανοίξουμε ένα εισιτήριο για προβλήματα με τον μεταφορέα;

1. Χώρα και αριθμός που καλούνται:
2. Χώρα και πόλη του προσώπου που καλεί να δοκιμάσει:
3. Tester αριθμός καλεί από:
4. Αριθμός τηλεφώνου ή κινητό τηλέφωνο;
5. Σε ποιον μεταφορέα ανήκει αυτός ο αριθμός;
6. Ημερομηνία και ώρα της δοκιμαστικής κλήσης:
7. Ακριβή στοιχεία των σφαλμάτων ή της εμπειρίας όταν καλείτε:

**Comment by mypil** [comment]
@kmpaltas - Έχετε ενημερώσεις;
[Do you have updates?]

μπορείτε να απαντήσετε στις ερωτήσεις μας;
[Can you answer our questions?]

ευχαριστώ
[Thanks]

**Comment by cmcatee-MSFT** [comment]
@kmpaltas 
Please contact me at cmcatee@microsoft.com with the information above so we can troubleshoot this issue. Thank you.

Παρακαλώ επικοινωνήστε μαζί μου στο cmcatee@microsoft.com με τις παραπάνω πληροφορίες, ώστε να μπορέσουμε να αντιμετωπίσουμε αυτό το ζήτημα. Ευχαριστούμε.

**Comment by mypil** [comment]
@kmpaltas - We will close this issue now. If your phone issue is not resolved, please contact cmcatee@microsoft.com. Thanks.


θα κλείσουμε αυτό το ζήτημα τώρα. εάν το θέμα του τηλεφώνου σας δεν επιλυθεί, Παρακαλώ επικοινωνήστε  στο cmcatee@microsoft.com.  Ευχαριστούμε.
