### ISSUE TITLE
Impact to OneDrive sync client not explained in this article

### ISSUE THREAD

**Issue by lkuhn65** [MicrosoftDocs/OfficeDocs-O365ITPro#73]
The Organization name, if changed, directly impacts the folder name that the OneDrive Sync client creates on Windows workstations.  This must be called out here somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c73190-a61e-5d37-0ad7-cbc5731c3fc0
* Version Independent ID: ec796206-3bad-e391-dee7-1ce5423f7fbe
* Content: [Change your organization's address, technical contact, and more](https://docs.microsoft.com/en-us/office365/admin/manage/change-address-contact-and-more?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/change-address-contact-and-more.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/change-address-contact-and-more.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AndreaBarr** [comment]
@lkuhn65 Thank you for pointing this out to us

I will get this information over to the O365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by Weychris** [comment]
Agree, AND don't make the Organization Name too long if you want to sync Excel files! (max. 218 characters). Geeze Microsoft.

**Comment by rstern** [comment]
We just encountered this issue (staff cannot access Excel files due to length of path). We've counseled them to use fewer and shorter nested folders but we would also like to give them some more room by changing our company name from about 30 characters to its 6-character initialism. My concern is that the change might disconnect all the staff that are already synced to their one drives, requiring a manual re-sync. While I realize that would simply be logging in with their O365 credentials again I have a team with varied technical proficiencies and for some of them a pop-up for credentials can be an unnecessarily stressful experience. Which is all to say, does anyone know if changing the company name would be a smooth back-end-only process or should I anticipate having to manually reconfigure one drives for all staff?

**Comment by Weychris** [comment]
@rstern I'm just about to go through with this for a small 4 user site- changing the org name, maybe site name, and document library name to shortern up the file path.

**Comment by rstern** [comment]
@Weychris please let us know how it goes, and if you encounter any unexpected challenges. Much appreciated!

**Comment by gacarini** [comment]
@lkuhn65 I believe this issue can be closed as we've added a reference to the sync client for both Windows and Mac. Let me know if you have any feedback.

**Comment by AndreaBarr** [comment]
@lkuhn65 I am going to go ahead and close this issue. If this is not resolved please re-open this issue.
