### ISSUE TITLE
Office 365 Does Not Allow Edit to SPF Record

### ISSUE THREAD

**Issue by PaulPMooney** [MicrosoftDocs/OfficeDocs-O365ITPro#74]
The important section above says "If you already have an SPF record for your domain, don't create a new one for Office 365. Instead, add the required Office 365 values to the current record so that you have a single SPF record that includes both sets of values." The problem is when you open the panel in O365 to do this it says in red below the entry "You can't edit or remove the Office 365 SPF record: include:spf.protection.outlook.com". So I cannot change ~all to -all.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1ab25e-c8aa-14fc-9724-6917a985e0e7
* Version Independent ID: 52b8dbba-a313-e012-b81c-cba78597dcf8
* Content: [Create DNS records at any DNS hosting provider for Office 365](https://docs.microsoft.com/en-ie/office365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?redirectSourcePath=%252fen-us%252farticle%252fCreate-DNS-records-at-any-DNS-hosting-provider-for-Office-365-7b7b075d-79f9-4e37-8a9e-fb60c1d95166&view=o365-worldwide)
* Content Source: [Office365-Admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by AndreaBarr** [comment]
@PaulPMooney Thank you for this feedback

I am not sure why your not able to change this. I want to get you over to Support since they have more resources to dig in and find a solution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by aldoug** [comment]
There should be no requirement to change the SPF record for the .onmicrosoft.com domain, only for the vanity domains (additional accepted domains) associated with your tenant

**Comment by dj-burns** [comment]
> There should be no requirement to change the SPF record for the .onmicrosoft.com domain, only for the vanity domains (additional accepted domains) associated with your tenant

@aldoug , I have come across a requirement to edit the SPF record for the onmicrosoft.com domain and wondered if this could be done, even if this be via MS Support only.
Our situation is: CompanyA is in O365 using a 3rdparty Email hygiene service (eg: Mimecast), they share a file from SharePoint Online with CompanyB, this email is sent from no-reply@companyA.onmicrosoft.com. 
CompanyB is following email security best practice and Rejecting SPF hard fails.
However the 'Sharing' email from CompanyA is sent via Mimecast as this is the outbound email flow from their O365 Tenant, so when CompanyB receives the email it is rejected due to the SPF record for CompanyA.onmicrosoft.com being set to 'v=spf1 include:spf.protection.outlook.com -all'.
I understand that we can ask ComapnyB to add an exclusion, however this does not resolve the issue and I can only see this becoming more of an issue as more companies increase email security.
I would appreciate your thoughts on this?
Thanks, Duncan
