### ISSUE TITLE
This page dows not take into account licenses acquired through CSP?

### ISSUE THREAD

**Issue by HenrikMejnhardtNielsen** [MicrosoftDocs/OfficeDocs-O365ITPro#745]
The "You bought your subscription through a partner" does not take into account licenses acquired through CSP?
It talks about VLSC (The old way of buying through OPEN).
Please update to reflect CSP acquired licenses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 113d825e-0bf2-935c-d143-9cafc11b69ad
* Version Independent ID: e953f652-7060-23e2-1a06-5c912d5c91b3
* Content: [Remove licenses from your Office 365 for business subscription](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/remove-licenses-from-subscription?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/remove-licenses-from-subscription.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/remove-licenses-from-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@HenrikMejnhardtNielsen - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by cmcatee-MSFT** [comment]
@HenrikMejnhardtNielsen The section [You bought your subscription through a partner](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/remove-licenses-from-subscription?view=o365-worldwide#you-bought-your-subscription-through-a-partner) stated that if you bought your subscription through a partner, you can't remove licenses, the partner has to do that for you. This also applies to CSP. I've updated that section so that is clearer. Hope this helps clarify.

**Comment by mypil** [comment]
@HenrikMejnhardtNielsen - From our understanding, the issue you raised has been answered by cmcatee-MSFT. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
