### ISSUE TITLE
Modern authentication option from web gui, never worked for me.

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/OfficeDocs-O365ITPro#758]
I've never been able to find this in the admin panel (any version, new or old)
but the powershell option for this always works.
Maybe include something like below? As it really mucks things up if you assume MA is enabled and its not. ( I think there might be a bug in the admin pages so if it thinks its enabled it doesn't show but really its not enabled. I've certainly had issues till I do the below at which point its all expected behaviour with MA where applicable.)

Set-ExecutionPolicy RemoteSigned

$UserCredential = Get-Credential

$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection

Set-OrganizationConfig -OAuth2ClientProfileEnabled $true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@mypil I am OK with the PowerShell being added, but I would like to see if @chrisda approves of it first.

**Comment by chrisda** [comment]
Modern Auth in Exchange Online is supposed to be on by default, but it wasn't in my very old tenant, and I had to turn it on manually by `-OAuth2ClientProfileEnabled $true`. We also document this [here](https://docs.microsoft.com/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online), so you might be able to link off instead of adding the steps.

MFA definitely requires Modern Auth, so you could perhaps incorporate this information into the topic as a _perquisite_ check for MFA? But do other services like SharePoint Online or Skype for Business Online require a similar check? Set-OrganizationConfig only affects Exchange Online.

**Comment by get-itips** [comment]
Hello @chrisda and @Sirkkuw thanks, based on the info you provided and some other I could get, I am proposing thru a pr adding a note with this information, please review the referenced PR.

**Comment by mypil** [comment]
@webstaff - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/635a9cac075a74ff2e7c6ca539a9bf7629680c70. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
