### ISSUE TITLE
Step #3 is inaccurate

### ISSUE THREAD

**Issue by jeffreyoliver** [MicrosoftDocs/OfficeDocs-O365ITPro#76]
The user account has a valid license yet the link to convert to a shared mailbox does not appear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@jeffreyoliver Thank you for this inquiry

I am not sure why the shared mailbox does not appear. I want to get you over to Support since they have more resources to help find a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
