### ISSUE TITLE
Please update documentation to reflect inability to move an smtp address

### ISSUE THREAD

**Issue by baltmanbrandes** [MicrosoftDocs/OfficeDocs-O365ITPro#805]
We have found and confirmed via support Ticket #:17306202, that although we can remove an smtp address from our on-prem Hybrid Exchange Server for a Remote User Mailbox that matches the UPN of the user, and we see AzureAD Connect send a deletion command, the smtp address does NOT actually get removed.  So if we add it to another user or DL we get the alerts about duplicate attributes from AzureAD sync.  The only workaround we could come up with was to change the login.  In this case it works because the user is an ex-employee.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6024c6e-1373-58de-ca8b-819a11693968
* Version Independent ID: 5d02bdc8-6e20-8b9b-942e-cca0e312cc5e
* Content: [Remove a former employee from Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@baltmanbrandes - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@baltmanbrandes Thank you for the feedback. What you said is correct w.r.t to removing an email address. The User Principal name automatically gets added as the email address, unless you change it manually. The workaround to remove the Smtp address would be to change the UPN( Login) as well. This document doesn't talk about removing an email address so I don't think we need to add this sentence.

Hope this helps!

Thanks
Sri

**Comment by baltmanbrandes** [comment]
Thanks Sri.  Where would it be appropriate to add to official Microsoft documentation that you cannot remove an email address that matches a UPN?  We can do that on-prem, AzureAD Connect shows it sending the command to remove it.  I had to spend time with Microsoft support on this for awhile before we came to conclusion that it couldn’t be done.  This should be reflected in some official MS doc.

**Comment by msbemba** [comment]
@baltmanbrandes I hear you! This article talks about how a Proxy address attribute is populated in Azure AD :-  https://support.microsoft.com/en-in/help/3190357/how-the-proxyaddresses-attribute-is-populated-in-azure-ad  while it doesn't talk much about why the UPN is added as a Proxy, This is by design, When an object is synchronized to Azure AD, the values that are specified in the proxyAddresses attribute in Active Directory are compared with Azure AD rules, and then the proxyAddresses attribute is populated in Azure AD. Therefore, the values of the proxyAddresses attribute for the object in Active Directory may not be the same as the values of the proxyAddresses attribute in Azure AD.

Default AD connect settings uses UPN as the primary SMTP address unless mentioned otherwise. 

Thanks
Sri

**Comment by mypil** [comment]
@baltmanbrandes - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
