### ISSUE TITLE
Notifications mailed to "Technical contact" in AAD and the primary email address registered in O365 admin center.

### ISSUE THREAD

**Issue by v-hakob** [MicrosoftDocs/OfficeDocs-O365ITPro#871]
One of our largest customer uses both O365 and Azure, and they would like to make sure they get all the notifications for what they are using. According to this document, the Technical contact in AAD is the email address for the primary technical person who administers your Office 365 subscription. Do "Technical contact" in AAD and the primary email address registered in O365 admin center receive the same types of notifications (e.g. Office 365 service status)? If there are more detailed info you can share with us, please advise. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c73190-a61e-5d37-0ad7-cbc5731c3fc0
* Version Independent ID: ec796206-3bad-e391-dee7-1ce5423f7fbe
* Content: [Change your organization's address, technical contact, and more](https://docs.microsoft.com/en-us/office365/admin/manage/change-address-contact-and-more?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/change-address-contact-and-more.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/change-address-contact-and-more.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@v-hakob Thank you for the feedback. The technical contact in AAD receives the service health status and not the address registered during the o365 setup. Meanwhile, If this is specific to Service status or health, we have a new feature which is going to be rolled out shortly and you can add multiple addresses for service health notifications- https://www.microsoft.com/en-gb/microsoft-365/roadmap?filters=&searchterms=24231

Stay informed through your preferred channel- service health dashboard in the Microsoft 365 admin center will enable you to sign up for notifications via email so that you can monitor the service and track issues through the channel you prefer.

Hope this Helps!

Thanks
Sri

**Comment by mypil** [comment]
@v-hakob - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
