### ISSUE TITLE
Where do I get the O365 Nameservers info to update GoDaddy?

### ISSUE THREAD

**Issue by xivizi** [MicrosoftDocs/OfficeDocs-O365ITPro#898]
In your "Change DNS management to Office 365" section and using the 'Setup my online services for me' option, everything works OK except that I don't get step 5 (we list the nameservers for O365 to update at your domain registrar).  

At the top of the 'Update DNS Settings' page there are green ticks against: add a domain, verify domain, set up your online services but not on 'Update DNS settings' which is still a blue circle. 

Even if I select 'I'll add the DNS records myself' it just says it is all done and does not provide the nameserver info to update at GoDaddy. 

Opening www.mysite.net in a browser still goes to a GoDaddy holding page and in the GoDaddy settings the nameservers are still pointing to GoDaddy.  

I've gone through this loop several times over a couple of days and it still finishes prior to step 5.

So how do I get the O365 Nameserver info to update GoDaddy?

Thank you - this is on an Office 365 Business Premium trial that I will shortly be subscribing to.

**Comment by xivizi** [comment]
.... just to clarify, the email side is working perfectly.  It is just the domain / URLs part that I cannot set up.  Thank you

**Comment by mypil** [comment]
@xivizi - Thank you for submitting feedback.

This doc - [Create DNS records at GoDaddy for Office 365](https://docs.microsoft.com/office365/admin/dns/create-dns-records-at-godaddy?view=o365-worldwide), may help provide more information to help fix your issue.

In case you still encounter some technical problems, I would recommend that you open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so that technical support can help in troubleshooting to resolve your issue.

I hope this gets you pointed in the right direction. Thank you.
