### ISSUE TITLE
Filter read correctly, but correct domain not applied

### ISSUE THREAD

**Issue by DFLiddle** [MicrosoftDocs/OfficeDocs-O365ITPro#90]
Greetings, all! I followed the instructions above for Scenario 2, setting a few policies like so:

New-EmailAddressPolicy -Name AbcGroups -IncludeUnifiedGroupRecipients -EnabledEmailAddressT
emplates "SMTP:@domain1.de" -ManagedByFilter {Office -eq 'ABC' -or EmailAddresses -like "*domain1.de*"} -Priority 1
New-EmailAddressPolicy -Name AbcGroups -IncludeUnifiedGroupRecipients -EnabledEmailAddressT
emplates "SMTP:@domain2.de" -ManagedByFilter {Office -eq 'DEF' -or EmailAddresses -like "*domain2.de*"} -Priority 2

When my test user, assigned to office "ABC", created its first group, all was well. When, however, I reassigned that user to office "DEF", the office attribute was applied correctly to the group name and alias, but the domain was not. The domain was that of the first policy. Have I done something wrong or misunderstood? Thank you for your advice!

P.S. What command, if any, can be used to retrieve and review the details of an email address policy? Get-EmailAddressPolicy, by itself, produces only a simple list.

P.P.S. The last command in that section refers to "-EnabledPrimarySMTPAddressTemplates", but it seems that it should be in the singular, i.e. "-EnabledPrimarySMTPAddressTemplate".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96002890-7e35-a0ab-a849-d94fef254fa8
* Version Independent ID: 2c4105db-b713-4829-393e-de355c5c60d4
* Content: [Choose the domain to use when creating Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/choose-domain-to-create-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/choose-domain-to-create-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/choose-domain-to-create-groups.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@DFLiddle Thank you for this inquiry

I am not sure how to address this policy issue. Let me get this over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dplotnikov** [comment]
@DFLiddle let me answer your questions.

I see that you have a couple of issues here

- You were using the same name for 2 groups and it shouldn't allow you to do that
- EmailAddresses filter should be surrounded by **, so in your example, it should be EmailAddresses -like "*domain1.de*" instead of EmailAddresses -like "domain1.de"

I was making some tests on my end and I think you were confused by filters. Obviously, you've updated the Office property but since you have OR condition, it was applied to your user and let me explain why. Looks like you have multiple domains in your Office 365 tenant and one of them is the main one and the second one is an alias but both of them available at the same time for a user, e.g. user1 could be reached via both user1@domain1.de and user1@domain2.de. Now you see why you are getting that and there is no technical issue here. I would suggest you adjust the filter and that should be it.

As for your second question, I'm not aware of any alternative for Get-EmailAddressPolicy cmdlet.

Thank you for finding the typo with EnabledPrimarySMTPAddressTemplates, I've created a pull request and the fix should be there after someone from Microsoft will merge it.

**Comment by DFLiddle** [comment]
Hi, @dplotnikov, and thank you for the input. Unfortunately, there seems to be some automatic formatting going on with these entries, so you wouldn't have seen that my commands did indeed contain the requisite asterisk ( * ) characters. The Markdown styling formats anything bounded by single \*asterisks\* as *italicized* text. By including an escape character ( \ ), one can cancel that formatting and avoid *actual* confusion.

The apparent use of the same name for two policies was a typo on my part in that initial post. The policies did not actually have the same name.

I have recreated my policies as before. These appear to work. I think that the priority levels may have been the cause of my problems. We'll see. I'm still in the early stages, so I can experiment without breaking anything.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed.
