### ISSUE TITLE
Include the list of Azure AD Roles

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/OfficeDocs-O365ITPro#98]
Some of the role names differ or don't appear when using the Get-AzureADDirectoryRole PowerShell cmdlet.

* "Global Administrator" is "Company Administrator"
* "Password Admin" is "Heldesk Administrator"
* "User Management Administrator" is "User Account Administrator"
* "Skype for Business Administrator" and "Compliance Administrator" don't show up

There are a few other differences.  The documentation should clearly list all of the AD tenant level roles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About Office 365 admin roles](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@sonika24 Could you handle this please?

**Comment by mypil** [comment]
@lesterw1 - we have already coordinated with the document author and got the confirmation that they
will add a note to this article that people who want to use PowerShell should read the Azure AD article and use those role names.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
